// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veterinary.Slices.Application.Data;

#nullable disable

namespace Veterinary.Slices.Application.Data.VeterinaryMigrations
{
    [DbContext(typeof(VeterinaryContext))]
    [Migration("20241031235930_ChangedAlternativePhoneNumberToBeNullable")]
    partial class ChangedAlternativePhoneNumberToBeNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Veterinary.Slices.Application.Data.Entities.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Annotations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("annotations")
                        .HasColumnOrder(3);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("crated_by")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created")
                        .HasColumnOrder(5);

                    b.Property<Guid>("PetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pet_id")
                        .HasColumnOrder(1);

                    b.Property<string>("Typeof")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type_of")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("consultations");
                });

            modelBuilder.Entity("Veterinary.Slices.Application.Data.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("AlternativePhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("alternative_phone_number")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("DateAddedToSystem")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_added_to_system")
                        .HasColumnOrder(6);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("first_name")
                        .HasColumnOrder(1);

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("identification")
                        .HasColumnOrder(5);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("last_name")
                        .HasColumnOrder(2);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("owners");
                });

            modelBuilder.Entity("Veterinary.Slices.Application.Data.Entities.OwnerPet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_id")
                        .HasColumnOrder(1);

                    b.Property<Guid>("PetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pet_id")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PetId");

                    b.ToTable("owners_pets");
                });

            modelBuilder.Entity("Veterinary.Slices.Application.Data.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("breed")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth")
                        .HasColumnOrder(5);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("full_name")
                        .HasColumnOrder(1);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender")
                        .HasColumnOrder(3);

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.ToTable("pets");
                });

            modelBuilder.Entity("Veterinary.Slices.Application.Data.Entities.Consultation", b =>
                {
                    b.HasOne("Veterinary.Slices.Application.Data.Entities.Pet", "Pet")
                        .WithMany("Consultations")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Veterinary.Slices.Application.Data.Entities.OwnerPet", b =>
                {
                    b.HasOne("Veterinary.Slices.Application.Data.Entities.Owner", "Owner")
                        .WithMany("OwnersPets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veterinary.Slices.Application.Data.Entities.Pet", "Pet")
                        .WithMany("OwnersPets")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Veterinary.Slices.Application.Data.Entities.Owner", b =>
                {
                    b.Navigation("OwnersPets");
                });

            modelBuilder.Entity("Veterinary.Slices.Application.Data.Entities.Pet", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("OwnersPets");
                });
#pragma warning restore 612, 618
        }
    }
}
